name: New issue
on:
  issues:
    types: [opened]
    branches:
      - main
      
  workflow_dispatch:

jobs:
  log-issue-detail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log issue details
        run: echo ${{ toJSON(github) }}

